CFLAGS  = -Wall -g -pthread
FUENTE1 = suma_parcial1.c
FUENTE2 = suma_parcial2.c
PROG1   = Suma1
PROG2   = Suma2

all :
	gcc $(CFLAGS) -o $(PROG1) $(FUENTE1)
	gcc $(CFLAGS) -o $(PROG2) $(FUENTE2)

clean :
	-rm $(PROG)
